Add variant and variant annotation conversion functions
fnothaft/adam pull request #11
Opened 2016-11-25 19:44 UTC by heuermh

Converted some of the variant and variant annotation conversions to functional style, please let me know if I'm on the right track.  We'll need `lineToExtractor` functions for VCF INFO headers and `make...` functions for `Variant` and `VariantAnnotation`.

2016-11-26 04:34 UTC, fnothaft reviewed
Variety of nits. Do you want to fix these nits here and then I'll merge, and then you'll open new PRs against the branch (e.g., with improved tests, etc)?

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    splitIds(vc).foreach(vb.setNames(_))
Won't this overwrite the `names` field in place multiple times?

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    Option(vc.getAttribute("SOMATIC").asInstanceOf[java.lang.Boolean]).foreach(vb.setSomatic(_))
Do you know how the flag fields are stored when parsing from VCF? I had a nasty surprise WRT this and the other attribute fields. I haven't looked ahead, but if you haven't added this yet, I would add a unit test with a VCF with a somatic call.

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    joinNames(v) match {
[Idiomatic scala](http://blog.originate.com/blog/2014/06/15/idiomatic-scala-your-options-do-not-match/) demands a `fold` here and not a `match`.

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      case (false, true)  => vcb.passFilters // log warning?
I would throw here.

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      vab.setAlleleCount(ac.get(index).asInstanceOf[java.lang.Integer])
Yeah, you're probably going to be disappointed. If my experience with HTSJDK's Genotype attributes is mirrored in the HTSJDK Variant world... all of the keys will be stored as strings.

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      vab.setAlleleCount(ac.get(index).asInstanceOf[java.lang.Integer])
Oh wait, never mind.

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      vab.setAlleleCount(ac.get(index).asInstanceOf[java.lang.Integer])
The APIs are different. Why would I expect anything? God, I hate HTSJDK.

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      vab.setAlleleCount(ac.get(index).asInstanceOf[java.lang.Integer])
You're good. That being said, I don't think you need the cast, no?

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    Option(va.getReadDepth).foreach(rd => vcb.attribute("AD", prependDefaultReferenceValue(rd)))
You've got a lot of long `Option(va.get<Fieldname>).foreach(` lines here and in the next few methods. Mind wrapping them?

2016-11-26 04:34 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    "-1," + v
Alternatively, you could just not prepend these, and ignore index = 0 for Number=R fields.

2016-11-26 04:35 UTC, fnothaft commented
Otherwise, LGTM!

2016-11-27 03:14 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    splitIds(vc).foreach(vb.setNames(_))
`splitIds` returns an `Option[java.util.List[String]]`

2016-11-27 03:16 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    joinNames(v) match {
Thanks for the link!  I try to refer to this one too http://blog.tmorris.net/posts/scalaoption-cheat-sheet/

2016-11-27 03:18 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      case (false, true)  => vcb.passFilters // log warning?
Agreed, this method could be re-written to look more like what you use with genotype filters, so that the behaviour is the same

2016-11-27 03:19 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      vab.setAlleleCount(ac.get(index).asInstanceOf[java.lang.Integer])
Maybe I did at some point?

2016-11-27 03:20 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    "-1," + v
Will htsjdk complain if you have a Number=R attribute with length=1 array?

2016-12-02 18:27 UTC, heuermh commented
Let me know how you'd like to proceed on this one.

I've a new pull request at https://github.com/bigdatagenomics/adam/pull/1297 that shouldn't be merged because it depends on a snapshot of bdg-formats.  A decision on https://github.com/bigdatagenomics/bdg-formats/issues/118 is blocking the bdg-formats release.

Those commits could be squashed and cherry picked (or otherwise merged) to your branch, and then I could proceed with additional commits on this pull request.  Even though I say those things like I know how to do them, I'm starting to get out of my git comfort zone.

2016-12-09 23:48 UTC, heuermh commented
With latest commit, compiles ok but fails 7 unit tests after un-ignoring all those ignored in fab986e.

2016-12-09 23:49 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    "-1," + v
This can be resolved after bdg-formats 119/120 is merged

2016-12-10 00:14 UTC, fnothaft commented
> With latest commit, compiles ok but fails 7 unit tests after un-ignoring all those ignored in fab986e.

w00t

Is this rebased on my latest updates to the `issues/1107-vcc-rewrite` branch? If so, I think the next step is to merge one of bigdatagenomics/bdg-formats#119 or bigdatagenomics/bdg-formats#120. My vote is for 120. Then we can dig into the remaining 7 unit tests.

Here's my proposal:

1. Let's merge bigdatagenomics/bdg-formats#120
2. I'll make a review pass over this
3. You can upgrade this to use bigdatagenomics/bdg-formats#120
4. Then you can fix the unit test failures
5. In parallel to 4, I can write some of the targeted unit tests (the per field conversion unit tests)

How's this sound?

2016-12-10 01:18 UTC, heuermh commented
+1

2016-12-10 04:28 UTC, fnothaft commented on adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
> +  sparkTest("can read an uncompressed BCFv2.2 file") { // see https://github.com/samtools/htsjdk/issues/507
Nice! Did htsjdk 2.7.0 add BCF2.2?

2016-12-10 04:48 UTC, fnothaft requested changes
Looks really good; I've suggested a couple of nitty changes inline.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      vb.setFiltersFailed(new java.util.ArrayList(vc.getFilters));
Drop `;` at end of line.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    Option(vc.getAttribute("DB").asInstanceOf[java.lang.Boolean])
Is this how the `getAttribute` function works on `VariantContext`? I remember having the sad finding that it didn't work like this on `Genotype`.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    if (af.size > index) {
OOC, might it be better here to check that `af.size` is either `> index` or `== 0`?

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    if (cigar.size > index) {
Ditto RE checking `cigar.size`.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    if (ad.size > (index + 1)) {
Ditto RE checking `ad.size`.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +  private[converters] def formatReadDepth(
I would prefer this function to be `formatAllelicDepth`. When I hear "read depth", I think "DP", not "AD".

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +  private[converters] def formatForwardReadDepth(
Ditto RE: `readDepth` vs `allelicDepth`

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +  private[converters] def formatReverseReadDepth(
Ditto RE: `readDepth` vs `allelicDepth`

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    if (adf.size > (index + 1)) {
Ditto RE checking `adf.size`.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    if (adr.size > (index + 1)) {
Ditto RE checking `adr.size`.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      // todo: I don't believe these are useful for INFO fields
Yeah, we needed them in the Genotype world for dealing with PL style fields.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      // todo: I don't believe these are useful for INFO fields
You shouldn't need an index array for INFO fields.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      val variant = variantBuilder.build
I wouldn't build here.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      variant
Instead, I would call `variantBuilder.build` here, after you attach the annotation.

2016-12-10 04:48 UTC, fnothaft commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      val builder = new VariantContextBuilder()
I would add an inline doc above this call noting that VCF is 1-based closed intervals. This is obvious from the code, but I always like to list it inline to call attention to the coordinate format change.

2016-12-10 16:16 UTC, heuermh commented on adam-core/src/test/scala/org/bdgenomics/adam/rdd/ADAMContextSuite.scala
> +  sparkTest("can read an uncompressed BCFv2.2 file") { // see https://github.com/samtools/htsjdk/issues/507
Nope, sorry, overzealous search-and-replace

2016-12-10 16:49 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +  private[converters] def formatReadDepth(
Yep, I thought about this a bunch over in bdg-formats.

VCF INFO reserved key DP is defined in the VCF spec as
```
DP : combined depth across samples, e.g. DP=154
```
and shown in an example as
```
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
```
It is `VCFConstants.DEPTH_KEY` and there is a `VCFStandardHeaderLine` in htsjdk, with the description
```java
new VCFInfoHeaderLine(VCFConstants.DEPTH_KEY, 1, VCFHeaderLineType.Integer,
  "Approximate read depth; some reads may have been filtered"));
```
Three slightly different definitions for the same thing.  In any case, it is a Number=1 attribute per site summed over all samples, which we drop because we split multi-attributes.

Then AD is new to the specification in VCF version 4.3, added in https://github.com/samtools/hts-specs/issues/78, defined as
```
AD, ADF, ADR: read depths for each allele; total (AD), on the forward (ADF) and the reverse (ADR) strand (Integer, Number=R)
```
In the issue linked above, no one can agree on the same wording for the definition
```
...GATK uses AD, which reports allele depths as a comma-separated list...
...comma-separated list of total depth for each allele...
##INFO=<ID=AD,Number=R,Type=Float,Description="Allele dosage">
##INFO=<ID=AD,Number=R,Type=Integer,Description="Allelic depths">
##INFO=<ID=AD,Number=R,Type=Integer,Description="Total allelic depths">
```
AD is defined as a constant in `VCFConstants` in htsjdk, but presumably only for FORMAT lines
```java
//AD isn't reserved, but is specifically handled by VariantContext
public static final String GENOTYPE_ALLELE_DEPTHS = "AD";
```
I see "allelic" or "for each allele" as redundant according to our split-allelic model; the alleles have already been split so the allelic read depth for a split `Variant`/`VariantAnnotation` is simply the read depth.

2016-12-10 16:50 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +    if (af.size > index) {
Not sure I'm following you, if the `af.size` is zero then we don't want to set the value

2016-12-10 16:51 UTC, heuermh commented on adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala
> +      variant
good catch

2016-12-17 07:22 UTC, fnothaft approved these changes

2016-12-17 07:22 UTC, merged